# Generated by Django 4.1 on 2022-10-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_ssh_public_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ssh_public_keys",
            field=models.TextField(blank=True, verbose_name="SSH public keys"),
        ),
    ]
