services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-root:/var/www/static:ro
  mysql:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=waggle"
      - "MYSQL_DATABASE=waggle"
  django:
    image: django
    build: .
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:80 --reload
    environment:
      - "DJANGO_SETTINGS_MODULE=config.settings.prod"
      # NOTE(sean) NEVER use this secret key in production! it is only for local dev!
      - "SECRET_KEY=KknZPfSExc_0N5GfSkMvHgNb9BnYPdTSpxdWxHIUCawnrBLGtRz5chKXd4qseYb72Cht29Rp70qskB4O"
      - "ALLOWED_HOSTS=localhost 127.0.0.1"
      - "CSRF_TRUSTED_ORIGINS=http://localhost http://127.0.0.1"
      # Database settings
      - "MYSQL_HOST=mysql"
      # NOTE(sean) we use the root user to allow django to setup / teardown test databases.
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=waggle"
      - "MYSQL_DATABASE=waggle"
      # Globus oauth2 / oidc settings (optional - see readme)
      - "OIDC_CLIENT_ID"
      - "OIDC_CLIENT_SECRET"
      - "OIDC_REDIRECT_PATH"
    volumes:
      - ./:/app:ro
      - static-root:/var/www/static:rw
volumes:
  static-root:
