services:
  mysql:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=waggle"
      - "MYSQL_DATABASE=waggle"
  django:
    image: django
    build: .
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:80 --reload --workers=3
    ports:
      - 127.0.0.1:8000:80
    environment:
      - "DJANGO_SETTINGS_MODULE=config.settings.prod"
      # Security settings. NEVER USE THESE SETTINGS IN PRODUCTION! THEY ARE FOR LOCAL TESTING ONLY!
      - "SECRET_KEY=django-insecure-$!4^oa&ws#nes5lo@y#7ljtsj_l+sau34a(8qb&cy-&8%gd-fp"
      - "ALLOWED_HOSTS=localhost,127.0.0.1"
      - "SESSION_COOKIE_SECURE=False"
      - "CSRF_COOKIE_SECURE=False"
      - "CSRF_TRUSTED_ORIGINS=http://localhost,http://127.0.0.1"
      - "SUCCESS_URL_ALLOWED_HOSTS=portal.sagecontinuum.org"
      # Database settings. We use the root user to allow django to setup / teardown test databases.
      - "DATABASE_URL=mysql://root:waggle@mysql/waggle"
      # Static file settings.
      - "STATIC_ROOT=/app/staticfiles"
      # Globus oauth2 / oidc settings (optional - see readme)
      - "OIDC_CLIENT_ID"
      - "OIDC_CLIENT_SECRET"
    volumes:
      - ./:/app:ro
