# Generated by Django 4.1.4 on 2022-12-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compute",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("core", "core"),
                    ("agent", "agent"),
                    ("shield", "shield"),
                    ("detector", "detector (deprecated! use enclosure instead!)"),
                    ("enclosure", "enclosure"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
