# Generated by Django 4.1.3 on 2022-11-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manifests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardware",
            name="hardware",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
