# Generated by Django 4.1.5 on 2023-01-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifests', '0002_alter_compute_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='computesensor',
            name='serial_no',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='computesensor',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='nodesensor',
            name='serial_no',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='nodesensor',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
