# Generated by Django 4.1.3 on 2022-11-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manifests", "0002_alter_hardware_hardware"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="compute",
            unique_together={("node", "hardware", "name")},
        ),
    ]
