# Generated by Django 4.2.1 on 2023-06-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0004_computehardware_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imei", models.CharField(max_length=64, verbose_name="IMEI")),
                ("imsi", models.CharField(max_length=64, verbose_name="IMSI")),
                ("iccid", models.CharField(max_length=64, verbose_name="ICCID")),
                (
                    "node",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="manifests.nodedata",
                    ),
                ),
            ],
        ),
    ]
