# Generated by Django 4.2.1 on 2023-06-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0005_modem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modem",
            name="imei",
            field=models.CharField(max_length=64, unique=True, verbose_name="IMEI"),
        ),
        migrations.AlterField(
            model_name="modem",
            name="node",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodedata",
            ),
        ),
    ]
