# Generated by Django 4.2.1 on 2023-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0007_modem_model_modem_sim_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modem",
            name="sim_type",
            field=models.CharField(
                choices=[
                    ("anl-nu", "Northwestern"),
                    ("anl-dawn", "ANL-DAWN"),
                    ("anl-vto", "ANL-VTO"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
                verbose_name="SIM Type",
            ),
        ),
    ]
