# Generated by Django 4.2.1 on 2023-06-04 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0008_alter_modem_sim_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modem",
            name="iccid",
            field=models.CharField(
                max_length=64,
                validators=[django.core.validators.RegexValidator("^[0-9]{20}$")],
                verbose_name="ICCID",
            ),
        ),
        migrations.AlterField(
            model_name="modem",
            name="imei",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[0-9]{15}$")],
                verbose_name="IMEI",
            ),
        ),
        migrations.AlterField(
            model_name="modem",
            name="imsi",
            field=models.CharField(
                max_length=64,
                validators=[django.core.validators.RegexValidator("^[0-9]{15}$")],
                verbose_name="IMSI",
            ),
        ),
        migrations.AlterField(
            model_name="modem",
            name="model",
            field=models.CharField(
                choices=[
                    ("mtcm2", "Multi-Tech MTCM2-L4G1-B03-KIT"),
                    ("other", "Other"),
                ],
                default="mtcm2",
                max_length=64,
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="modem",
            name="sim_type",
            field=models.CharField(
                choices=[
                    ("anl-nu", "Northwestern"),
                    ("anl-dawn", "ANL-DAWN"),
                    ("anl-vto", "ANL-VTO"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=64,
                verbose_name="SIM Type",
            ),
        ),
    ]
