# Generated by Django 4.2.1 on 2023-06-05 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0010_modem_carrier_alter_modem_iccid_alter_modem_imsi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modem",
            name="carrier",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[django.core.validators.RegexValidator("^[0-9]{,20}$")],
                verbose_name="Carrier Code",
            ),
        ),
    ]
