# Generated by Django 4.2.5 on 2023-10-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0011_alter_modem_carrier"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoRaWANDevice",
            fields=[
                (
                    "DevEUI",
                    models.CharField(
                        max_length=16, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("device_name", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "battery_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "expected_uplink_interval_sec",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lorawandevices",
                        to="manifests.nodedata",
                    ),
                ),
            ],
            options={
                "verbose_name": "LoRaWAN Device",
                "verbose_name_plural": "LoRaWAN Devices",
            },
        ),
    ]
