# Generated by Django 4.2.5 on 2023-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0011_alter_modem_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodedata",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
