# Generated by Django 4.2.5 on 2023-10-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0011_alter_modem_carrier"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoRaWANDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("device_name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("Lastseen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "battery_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lorawandevices",
                        to="manifests.nodedata",
                    ),
                ),
            ],
        ),
    ]
