# Generated by Django 4.2.5 on 2023-10-06 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0012_lorawandevice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lorawandevice",
            options={
                "verbose_name": "LoRaWAN Device",
                "verbose_name_plural": "LoRaWAN Devices",
            },
        ),
    ]
