# Generated by Django 4.2.5 on 2023-09-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0012_nodedata_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodedata",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="nodedata",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Node ID"),
        ),
    ]
