# Generated by Django 4.2.5 on 2023-09-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0013_nodedata_location_alter_nodedata_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodedata",
            name="location",
            field=models.TextField(blank=True, verbose_name="Location"),
        ),
    ]
