# Generated by Django 4.2.5 on 2023-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0015_nodedata_phase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodedata",
            name="location",
        ),
        migrations.AddField(
            model_name="nodedata",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
    ]
