# Generated by Django 4.2.5 on 2023-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0016_remove_nodedata_location_nodedata_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodedata",
            name="name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Node ID"),
        ),
    ]
