# Generated by Django 4.2.5 on 2023-09-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0017_alter_nodedata_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodedata",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Deployed", "Deployed"),
                    ("Maintenance", "Maintenance"),
                    ("Standby", "Standby"),
                    ("Awaiting Deployment", "Awaiting Deployment"),
                    ("Shipment Pending", "Shipment Pending"),
                ],
                max_length=30,
                null=True,
                verbose_name="Phase",
            ),
        ),
    ]
