# Generated by Django 4.2.5 on 2023-09-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0018_alter_nodedata_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodedata",
            name="registered_at",
            field=models.DateTimeField(null=True),
        ),
    ]
