# Generated by Django 4.2.5 on 2023-09-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0020_alter_nodedata_registered_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vsn", models.CharField(max_length=10, verbose_name="VSN")),
                ("shield", models.BooleanField(default=False, verbose_name="Shield")),
                ("modem", models.BooleanField(default=False, verbose_name="Modem")),
                (
                    "sim_type",
                    models.CharField(
                        choices=[
                            ("anl-nu", "Northwestern"),
                            ("anl-dawn", "ANL-DAWN"),
                            ("anl-vto", "ANL-VTO"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=64,
                        verbose_name="SIM Type",
                    ),
                ),
                (
                    "bottom_camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="manifests.sensorhardware",
                    ),
                ),
                (
                    "left_camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="manifests.sensorhardware",
                    ),
                ),
                (
                    "right_camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="manifests.sensorhardware",
                    ),
                ),
                (
                    "top_camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="manifests.sensorhardware",
                    ),
                ),
            ],
        ),
    ]
