# Generated by Django 4.2.5 on 2023-09-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0021_nodebuild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodebuild",
            name="bottom_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="manifests.sensorhardware",
            ),
        ),
        migrations.AlterField(
            model_name="nodebuild",
            name="left_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="manifests.sensorhardware",
            ),
        ),
        migrations.AlterField(
            model_name="nodebuild",
            name="right_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="manifests.sensorhardware",
            ),
        ),
        migrations.AlterField(
            model_name="nodebuild",
            name="sim_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("anl-nu", "Northwestern"),
                    ("anl-dawn", "ANL-DAWN"),
                    ("anl-vto", "ANL-VTO"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=64,
                null=True,
                verbose_name="SIM Type",
            ),
        ),
        migrations.AlterField(
            model_name="nodebuild",
            name="top_camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="manifests.sensorhardware",
            ),
        ),
    ]
