# Generated by Django 4.2.5 on 2023-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0022_alter_nodebuild_bottom_camera_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodebuild",
            name="vsn",
            field=models.CharField(max_length=10, unique=True, verbose_name="VSN"),
        ),
    ]
