# Generated by Django 4.2.5 on 2023-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0024_alter_nodebuild_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodebuild",
            name="sim_type",
        ),
        migrations.AddField(
            model_name="nodebuild",
            name="modem_sim_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("anl-nu", "Northwestern"),
                    ("anl-dawn", "ANL-DAWN"),
                    ("anl-vto", "ANL-VTO"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=64,
                null=True,
                verbose_name="Modem SIM Type",
            ),
        ),
    ]
