# Generated by Django 4.2.5 on 2023-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0025_remove_nodebuild_sim_type_nodebuild_modem_sim_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodebuild",
            name="agent",
            field=models.BooleanField(default=False, verbose_name="Agent"),
        ),
    ]
