# Generated by Django 4.2.5 on 2023-09-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0026_nodebuild_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodebuild",
            name="type",
            field=models.CharField(
                choices=[("Blade", "Blade"), ("WSN", "Wsn")],
                default="WSN",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
