# Generated by Django 4.2.5 on 2023-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0027_nodebuild_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodebuild",
            name="type",
            field=models.CharField(
                choices=[("Blade", "Blade"), ("WSN", "WSN")],
                default="WSN",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
