# Generated by Django 4.2.5 on 2023-09-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0029_nodebuild_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeBuildProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
            ],
        ),
        migrations.AlterField(
            model_name="nodebuild",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodebuildproject",
            ),
        ),
    ]
