# Generated by Django 4.2.5 on 2023-09-30 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0030_nodebuildproject_alter_nodebuild_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nodebuildproject",
            options={"verbose_name_plural": "Node Build Projects"},
        ),
        migrations.AlterField(
            model_name="nodebuild",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodebuildproject",
            ),
        ),
    ]
