# Generated by Django 4.2.5 on 2023-09-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0031_alter_nodebuildproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodebuild",
            name="enclosure_rpi",
            field=models.BooleanField(default=False, verbose_name="Enclosure RPi"),
        ),
    ]
