# Generated by Django 4.2.7 on 2023-11-08 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0035_lorawanconnection_lorawandevice_lorawankeys_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodedata",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodebuildproject",
            ),
        ),
    ]
