# Generated by Django 4.2.5 on 2023-12-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0036_nodedata_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lorawandevice",
            name="device_name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
