# Generated by Django 4.2.7 on 2023-11-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0036_nodedata_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodedata",
            name="commissioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="gps_alt",
            field=models.FloatField(blank=True, null=True, verbose_name="Altitude"),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="location",
            field=models.TextField(blank=True, verbose_name="Location"),
        ),
    ]
