# Generated by Django 4.2.5 on 2023-12-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0037_alter_nodedata_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computehardware",
            name="hw_model",
            field=models.CharField(
                help_text="This is the model number of your sensor preferably without the manufacturer name in it.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="resourcehardware",
            name="hw_model",
            field=models.CharField(
                help_text="This is the model number of your sensor preferably without the manufacturer name in it.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sensorhardware",
            name="hw_model",
            field=models.CharField(
                help_text="This is the model number of your sensor preferably without the manufacturer name in it.",
                max_length=30,
            ),
        ),
    ]
