# Generated by Django 4.2.7 on 2024-02-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0039_alter_computehardware_hw_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_notes", models.TextField(blank=True, null=True)),
                (
                    "street_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state_province",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AddField(
            model_name="nodedata",
            name="address_new",
            field=models.ManyToManyField(
                blank=True, related_name="nodes", to="manifests.address"
            ),
        ),
    ]
