# Generated by Django 4.2.7 on 2024-04-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0039_alter_computehardware_hw_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeBuildProjectFocus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
            ],
            options={
                "verbose_name_plural": "Node Build Project Focuses",
            },
        ),
        migrations.CreateModel(
            name="NodeBuildProjectPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
            ],
            options={
                "verbose_name_plural": "Node Build Project Partners",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Site ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Site Description"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sites",
            },
        ),
        migrations.AddField(
            model_name="nodedata",
            name="commissioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="gps_alt",
            field=models.FloatField(blank=True, null=True, verbose_name="Altitude"),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="location",
            field=models.TextField(
                blank=True, db_column="location", verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="type",
            field=models.CharField(
                choices=[("Blade", "Blade"), ("WSN", "WSN")],
                default="WSN",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="nodebuild",
            name="focus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodebuildprojectfocus",
            ),
        ),
        migrations.AddField(
            model_name="nodebuild",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodebuildprojectpartner",
            ),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="focus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodebuildprojectfocus",
            ),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodebuildprojectpartner",
            ),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="site_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nodes",
                to="manifests.site",
            ),
        ),
    ]
