# Generated by Django 4.2.7 on 2024-10-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0041_compute_is_active_computesensor_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lorawanconnection",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this item is currently expected to be active. Unselect this to temporarily mark the item as inactive without deleting it, maintaining its configuration.",
                verbose_name="active",
            ),
        ),
    ]
