# Generated by Django 4.2.7 on 2024-10-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0042_lorawanconnection_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="id",
            field=models.CharField(
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Site ID",
            ),
        ),
    ]
