# Generated by Django 4.2.7 on 2024-02-13 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0042_remove_nodedata_address_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFocus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
            ],
            options={
                "verbose_name_plural": "Project Focus",
            },
        ),
        migrations.AddField(
            model_name="nodedata",
            name="focus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.projectfocus",
            ),
        ),
    ]
