# Generated by Django 4.2.7 on 2024-02-13 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0043_projectfocus_nodedata_focus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodedata",
            name="location",
        ),
    ]
