# Generated by Django 4.2.7 on 2025-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0043_alter_site_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodedata",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Deployed", "Deployed"),
                    ("Maintenance", "Maintenance"),
                    ("Standby", "Standby"),
                    ("Awaiting Deployment", "Awaiting Deployment"),
                    ("Shipment Pending", "Shipment Pending"),
                    ("Retired", "Retired"),
                ],
                max_length=30,
                null=True,
                verbose_name="Phase",
            ),
        ),
    ]
