# Generated by Django 4.2.7 on 2024-02-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0048_alter_nodebuildprojectfocus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodedata",
            name="nodebuild",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manifests.nodebuild",
            ),
        ),
        migrations.AddField(
            model_name="nodedata",
            name="type",
            field=models.CharField(
                choices=[("Blade", "Blade"), ("WSN", "WSN")],
                default="WSN",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
