# Generated by Django 4.2.7 on 2024-02-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0049_nodedata_nodebuild_nodedata_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Site ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Site Description"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sites",
            },
        ),
        migrations.AddField(
            model_name="nodedata",
            name="site_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nodes",
                to="manifests.site",
            ),
        ),
    ]
