# Generated by Django 4.2.7 on 2024-02-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0050_site_nodedata_site_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="id",
            field=models.CharField(
                max_length=4,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Site ID",
            ),
        ),
    ]
