# Generated by Django 4.2.7 on 2024-03-14 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manifests", "0051_alter_site_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodedata",
            name="nodebuild",
        ),
    ]
