# Generated by Django 4.2.5 on 2023-11-03 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("node_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={},
        ),
    ]
