# Generated by Django 4.2.23 on 2025-07-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node_auth", "0002_alter_token_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="wg_priv_key",
            field=models.CharField(
                blank=True,
                max_length=44,
                null=True,
                verbose_name="WireGuard Private Key",
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="wg_pub_key",
            field=models.CharField(
                blank=True,
                max_length=44,
                null=True,
                verbose_name="WireGuard Public Key",
            ),
        ),
    ]
