# Generated by Django 4.1 on 2022-09-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nodemembership",
            name="app_nodemembership_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="usermembership",
            name="app_profilemembership_uniq",
        ),
    ]
