# Generated by Django 4.1.1 on 2022-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemembership",
            name="allow_view",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether user has view access to project.",
                verbose_name="View?",
            ),
        ),
    ]
