# Generated by Django 4.1.1 on 2022-09-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profilemembership_allow_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="mac",
            field=models.CharField(
                max_length=16, null=True, unique=True, verbose_name="MAC"
            ),
        ),
    ]
