# Generated by Django 4.1.1 on 2022-10-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_globus_preferred_username_user_globus_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="globus_subject",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="Globus Subject"
            ),
        ),
    ]
