# Generated by Django 4.1.4 on 2023-02-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_submit_apps",
            field=models.BooleanField(default=False, verbose_name="Submit Apps?"),
        ),
    ]
