# Generated by Django 4.1.1 on 2022-10-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_user_globus_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="globus_preferred_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Globus Preferred Username",
            ),
        ),
    ]
