# Generated by Django 4.1 on 2022-09-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_node_mac"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
