# Generated by Django 4.1.4 on 2023-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_user_can_submit_apps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="can_submit_apps",
        ),
        migrations.AddField(
            model_name="user",
            name="is_app_developer",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can develop and submit apps to ECR.",
                verbose_name="App developer status",
            ),
        ),
    ]
