# Generated by Django 4.1.1 on 2022-10-13 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_user_globus_preferred_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="globus_preferred_username",
        ),
        migrations.RemoveField(
            model_name="user",
            name="globus_subject",
        ),
        migrations.CreateModel(
            name="GlobusAccount",
            fields=[
                (
                    "subject",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="Subject"
                    ),
                ),
                (
                    "preferred_username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Preferred Username",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="globus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
