# Generated by Django 4.1.4 on 2023-02-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_user_can_submit_apps_user_is_app_developer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_app_developer",
        ),
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is approved to perform basic tasks. (Ex. submit app to ECR)",
                verbose_name="Approval status",
            ),
        ),
    ]
