# Generated by Django 4.1.1 on 2022-10-13 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_globusaccount_email_globusaccount_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globusaccount",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oidc_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
