# Generated by Django 4.2 on 2023-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_user_is_app_developer_user_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is approved to perform basic tasks such as submitting apps to ECR.",
                verbose_name="Approval status",
            ),
        ),
    ]
