# Generated by Django 4.1.1 on 2022-10-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_globusaccount_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GlobusAccount",
        ),
    ]
