# Generated by Django 4.2.5 on 2023-12-04 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_user_is_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="node",
            options={"verbose_name": "node", "verbose_name_plural": "nodes"},
        ),
        migrations.AddField(
            model_name="node",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this node should be treated as active. Unselect this instead of deleting nodes.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
