# Generated by Django 4.2.5 on 2023-12-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_node_options_node_date_joined_node_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="last_login",
        ),
        migrations.AddField(
            model_name="node",
            name="last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last updated"
            ),
        ),
    ]
