# Generated by Django 4.2.5 on 2023-12-07 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_node_last_login_node_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="last_updated",
        ),
    ]
