# Generated by Django 4.2.7 on 2024-01-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_remove_node_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="files_public",
            field=models.BooleanField(default=False),
        ),
    ]
