# Generated by Django 4.2.23 on 2025-07-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_node_commissioning_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="vpn_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="VPN IP"
            ),
        ),
    ]
