services:
  github:
    url: https://raw.githubusercontent.com/waggle-sensor/waggle-policies
    credentials:
      bearer: #TODO: Add the waggle generated token
        scheme: "Bearer"
        token: "${BUNDLES_GITHUB_TOKEN}"

bundles:
  waggle-Policies:
    service: github
    resource: "dev/bundles/waggle-auth-app.tar.gz"
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120
