services:
  django:
    build:
      context: ../../
      dockerfile: ./env/dev/Dockerfile 
    restart: always
    command: >
      sh -c "python manage.py migrate && 
             python manage.py createsuperuser --noinput || true && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      # superuser login
      - "DJANGO_SETTINGS_MODULE=config.settings.dev"
      - "DJANGO_SUPERUSER_USERNAME=admin"
      - "DJANGO_SUPERUSER_EMAIL=admin@example.com"
      - "DJANGO_SUPERUSER_PASSWORD=admin"
      # Static file settings.
      - "STATIC_ROOT=/app/staticfiles"
    volumes:
      - ../../:/app:rw
  opa:
    image: openpolicyagent/opa:0.70.0
    platform: linux/amd64
    command:
      - run
      - /policies
      - --server
      - --addr
      - 0.0.0.0:8181
      - --watch 
      - "--ignore=.*"
      - --log-level
      - debug
      - "--log-format=json-pretty"
      - --set
      - "decision_logs.console=true"
      - --v1-compatible
    volumes:
      - ../../opa/policies:/policies
    ports:
      - "8181:8181" 