services:
  django:
    build:
      context: ../../
      dockerfile: ./env/dev/Dockerfile 
    restart: always
    command: >
      sh -c "python manage.py migrate && 
             python manage.py createsuperuser --noinput || true && 
             printenv > /etc/environment && 
             cron &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      # superuser login
      - "DJANGO_SETTINGS_MODULE=config.settings.dev"
      - "DJANGO_SUPERUSER_USERNAME=admin"
      - "DJANGO_SUPERUSER_EMAIL=admin@example.com"
      - "DJANGO_SUPERUSER_PASSWORD=admin"
      # Static file settings.
      - "STATIC_ROOT=/app/staticfiles"
      # S3 settings
      - "S3_ENDPOINT=sdsc.osn.xsede.org"
      - "S3_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${S3_SECRET_KEY}"
      - "S3_BUCKET_NAME=sage"
      - "S3_ROOT_FOLDER=node-data"
      - "S3_REGION=us-west-2"
      # Pelican settings
      - "PELICAN_KEY_PATH=${PELICAN_KEY_PATH}"
      - "PELICAN_ALGORITHM=ES256"
      - "PELICAN_KEY_ID=${PELICAN_KEY_ID}"
      - "PELICAN_ISSUER=https://sagecontinuum.org"
      - "PELICAN_LIFETIME=60"
      - "PELICAN_ROOT_URL=https://nrdstor.nationalresearchplatform.org:8443/sage"
      - "PELICAN_ROOT_FOLDER=/node-data"
      - "INV_TOOLS_REPO=/app/waggle-inventory-tools"
      #NOTE: uncomment these lines for automatic updates of the inventory tools repo
      # - "INV_TOOLS_REPO=https://github.com/waggle-sensor/waggle-inventory-tools.git"
      # - "INV_TOOLS_TOKEN=${INV_TOOLS_TOKEN}" 
      - "INV_TOOLS_SSH_TOOLS=/root/git"
      - "INV_TOOLS_SSH_CONFIG=/root/ssh"
      - "INV_TOOLS_SSH_TOOLS_PW=${INV_TOOLS_SSH_TOOLS_PW}" 
    env_file:
      - .env
    volumes:
      - ../../:/app:rw
      - /Users/franciscolozano/waggle_inv_tools/git:/root/git #TODO: change this to another path not Users
      - /Users/franciscolozano/waggle_inv_tools/ssh:/root/ssh #TODO: change this to another path not Users
      - /Users/franciscolozano/waggle_inv_tools/waggle-inventory-tools:/app/waggle-inventory-tools #TODO: change this to another path not Users
