services:
  django:
    build:
      context: ../../
      dockerfile: ./env/dev/Dockerfile 
    restart: always
    command: >
      sh -c "python manage.py migrate && 
             python manage.py createsuperuser --noinput || true && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      # superuser login
      - "DJANGO_SETTINGS_MODULE=config.settings.dev"
      - "DJANGO_SUPERUSER_USERNAME=admin"
      - "DJANGO_SUPERUSER_EMAIL=admin@example.com"
      - "DJANGO_SUPERUSER_PASSWORD=admin"
      # Static file settings.
      - "STATIC_ROOT=/app/staticfiles"
      # S3 settings
      - "S3_ENDPOINT=sdsc.osn.xsede.org"
      - "S3_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${S3_SECRET_KEY}"
      - "S3_BUCKET_NAME=sage"
      - "S3_ROOT_FOLDER=node-data"
      - "S3_REGION=us-west-2"
      # Pelican settings
      - "PELICAN_KEY_PATH=${PELICAN_KEY_PATH}"
      - "PELICAN_ALGORITHM=ES256"
      - "PELICAN_KEY_ID=${PELICAN_KEY_ID}"
      - "PELICAN_ISSUER=https://sagecontinuum.org"
      - "PELICAN_LIFETIME=60"
      - "PELICAN_ROOT_URL=https://nrdstor.nationalresearchplatform.org:8443/sage"
      - "PELICAN_ROOT_FOLDER=/node-data"
    volumes:
      - ../../:/app:rw
  opa:
    image: openpolicyagent/opa:0.70.0
    platform: linux/amd64
    command:
      - run
      - "--config-file=/bundles-config.yaml"
      - --server
      - --addr
      - 0.0.0.0:8181
      - --watch 
      - "--ignore=.*"
      - --log-level
      - debug
      - "--log-format=json-pretty"
      - --set
      - "decision_logs.console=true"
      - --v1-compatible
    volumes:
      - ./bundles-config.yaml:/bundles-config.yaml
    ports:
      - "8181:8181" 